# Generated by Django 3.2.19 on 2023-06-19 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('idd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeOfBirth', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('mail', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('last_visit', models.TextField()),
                ('alcohol', models.TextField()),
                ('smoke', models.TextField()),
                ('drugs', models.TextField()),
                ('religion', models.CharField(max_length=255)),
                ('allergies', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male')], max_length=100)),
                ('idd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
