# Generated by Django 3.2.19 on 2023-06-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230619_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='alcohol',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='drugs',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='smoke',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=100),
        ),
    ]
