# Generated by Django 3.2.19 on 2023-06-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230619_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='placeOfBirth',
            new_name='place_of_birth',
        ),
    ]
