# Generated by Django 3.2.19 on 2023-06-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230620_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_diagnostic',
            field=models.TextField(null=True),
        ),
    ]
