# Generated by Django 3.2.19 on 2023-06-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_patient_last_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='meds',
            field=models.TextField(null=True),
        ),
    ]
