# Generated by Django 3.2.19 on 2023-06-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230620_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Hospital',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
