# Generated by Django 3.2.19 on 2023-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_doctor_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=250, null=True)),
                ('prescription', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
