# Generated by Django 3.2.19 on 2023-06-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.CharField(choices=[('Monday Jan 6', 'Monday')], max_length=100, null=True)),
            ],
        ),
    ]
