# Generated by Django 3.2.19 on 2023-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='appointment',
            field=models.CharField(choices=[('Tuesday', 'Monday Jan 7'), ('Friday', 'Monday Jan 10'), ('Monday Jan 6', 'Monday'), ('Saturday', 'Monday Jan 11'), ('Thursday', 'Monday Jan 9'), ('Wednesday', 'Monday Jan 8')], max_length=100, null=True),
        ),
    ]
