# Generated by Django 3.2.19 on 2023-06-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_book_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availability_hours',
            field=models.CharField(choices=[('ten', '10:00 - 10:30'), ('eight', '8:30 - 9:00'), ('twelve ', '12:30 - 13:00'), ('fifteen', '15:00 - 15:30')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='appointment',
            field=models.CharField(choices=[('Thursday', 'Monday Jan 9'), ('Saturday', 'Monday Jan 11'), ('Tuesday', 'Monday Jan 7'), ('Monday Jan 6', 'Monday Jan 6'), ('Wednesday', 'Monday Jan 8'), ('Friday', 'Monday Jan 10')], max_length=100, null=True),
        ),
    ]
